# Image: https://hub.docker.com/layers/arm64v8/ros/humble-perception/images/sha256-18f05b82978b803530614f9058bde6ffa0832f21388debf30c2186d9944c0c63?context=explore
FROM ros:humble-perception

RUN apt update

RUN apt install -y gnupg2 curl lsb-core vim wget python3-pip libpng16-16 libjpeg-turbo8 libtiff5

RUN apt install -y \
    # Base tools
    cmake \
    build-essential \
    git \
    unzip \
    pkg-config \
    python3-dev \
    # OpenCV dependencies
    python3-numpy \
    # Pangolin dependencies
    libgl1-mesa-dev \
    libglew-dev \
    libpython3-dev \
    libeigen3-dev \
    apt-transport-https \
    ca-certificates\
    software-properties-common \
    libcanberra-gtk-module \
    gstreamer1.0-plugins-good
RUN apt update


# Build OpenCV
RUN apt install -y python3-dev python3-numpy python2-dev
RUN apt install -y libavcodec-dev libavformat-dev libswscale-dev
RUN apt install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
RUN apt install -y libgtk-3-dev
RUN apt install -y sudo apt libcanberra-gtk-module libcanberra-gtk3-module

RUN cd /tmp && git clone https://github.com/opencv/opencv.git && \
    cd opencv && \
    git checkout 4.4.0 && mkdir build && cd build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_EXAMPLES=OFF  -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local .. && \
    make -j8 && make install && \
    cd / && rm -rf /tmp/opencv

# Build Pangolin
RUN cd /tmp && git clone https://github.com/stevenlovegrove/Pangolin && \
    cd Pangolin && git checkout v0.9.1 && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_INSTALL_PREFIX=/usr/local .. && \
    make -j8 && make install && \
    cd / && rm -rf /tmp/Pangolin

# Get ORB_SLAM3_ROS2 wrapper
RUN cd /home/$USER && mkdir -p colcon_ws/src && \
    cd colcon_ws/src && \
    git clone -b odom https://github.com/dirksavage88/ORB_SLAM3_ROS2.git && \
    git clone https://github.com/dirksavage88/ros2_usb_camera.git && \
    git clone https://github.com/dirksavage88/side_x_side_stereo.git

# Extract default vocab tar
RUN cd /home/$USER/colcon_ws/src/ORB_SLAM3_ROS2/vocabulary && \
    tar -xf ORBvoc.txt.tar.gz

# ORBEC deps
RUN apt install -y libgflags-dev nlohmann-json3-dev \
    ros-humble-image-transport ros-humble-image-transport-plugins ros-humble-compressed-image-transport \
    ros-humble-image-publisher ros-humble-camera-info-manager \
    ros-humble-diagnostic-updater ros-humble-diagnostic-msgs ros-humble-statistics-msgs ros-humble-xacro \
    ros-humble-backward-ros libdw-dev libssl-dev mesa-utils libgl1 libgoogle-glog-dev

# ORBBEC drivers
RUN apt update && apt-get install -y ros-humble-orbbec-camera ros-humble-orbbec-description

# Build ORB-SLAM3 with its dependencies.
RUN apt update && apt-get install ros-humble-pcl-ros tmux -y
RUN apt install ros-humble-nav2-common x11-apps nano -y
COPY ORB_SLAM3 /home/orb/ORB_SLAM3
RUN cd /home/orb/ORB_SLAM3 && mkdir build && ./build.sh && cp lib/libORB_SLAM3.so /usr/local/lib
RUN ldconfig

