version: "3"
services:
  orb_slam3_ros2:
    image: orb-slam-3-ros2:v3
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #X11
      - /home/savagerobotsorin/.Xauthority:/root/.Xauthority:rw
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    entrypoint: /bin/bash
    command: >
      -c "source /opt/ros/humble/setup.bash && cd /home/colcon_ws && colcon build --symlink-install && source install/setup.bash"
